# Site settings
title:          空文
description:    "hi"
baseurl:        ""
url:            "https://xukongwen.github.io"

# Author
author:
  name:         kongwen
  url:          https://xukongwen.github.io
  email:        oabdao@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
