baseURL = "https://xukongwen.github.io/"
languageCode = "en-us"
title = "空文"
theme = "book"

[params]
  google_fonts = [
    ["Noto Serif SC", "400"],
  ]

  heading_font = "Noto Serif SC"
  body_font = "Noto Serif SC"