baseURL = "https://xukongwen.github.io/"
languageCode = "en-us"
title = "空文"
theme = "book"

[params]
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]

  heading_font = "Fira Code"
  body_font = "Open Sans"